### ISSUE TITLE
如何自动填写周报

### ISSUE THREAD

**Issue by Harry2336** [XuanRanDev/Auto-GongXueYun#17]
大佬，请问如何启用自动填写周报功能啊？还有就是这个功能填报的内容是啥啊？

**Comment by XuanRanDev** [comment]
看文档下面

**Comment by Harry2336** [comment]
大佬您的文档我看过了，更新日志里您只说“这些新功能不会往master合并”“不再更新不代表无法正常使用”，但是并未提及如何启用和启用后的效果

**Comment by XuanRanDev** [comment]
> 大佬您的文档我看过了，更新日志里您只说“这些新功能不会往master合并”“不再更新不代表无法正常使用”，但是并未提及如何启用和启用后的效果

还不清除吗，我说了不会往master合并，所以你们看不到。
![微信截图_20230102183930.png](https://tc.xuanran.cc/2023/01/02/5627c0a713cdc.png)

**Comment by XuanRanDev** [comment]
> 大佬您的文档我看过了，更新日志里您只说“这些新功能不会往master合并”“不再更新不代表无法正常使用”，但是并未提及如何启用和启用后的效果

不再更新不代表无法正常使用指的是现在的打卡功能
