### ISSUE TITLE
关于自己服务器部署不能签到

### ISSUE THREAD

**Issue by 96368a** [XuanRanDev/Auto-GongXueYun#18]
工学云貌似拉黑了云服务器厂商的ip，我的三台机器，腾讯云轻量云广州、香港，阿里轻量云成都，均无法签到，测试发现是访问不了https://api.moguding.net:9000

[![12222](https://kjimg10.360buyimg.com/ott/jfs/t1/60680/29/17031/38009/63ba2557Fc750afc0/f9486f9136461c94.png)](https://kjimg10.360buyimg.com/ott/jfs/t1/60680/29/17031/38009/63ba2557Fc750afc0/f9486f9136461c94.png)

可以用
``` curl https://api.moguding.net:9000 ```
测试ip是否被拉黑，下图为没有被拉黑返回的信息，超时或者显示如上图就是被拉黑了
[![uTools_1673143795620.png](https://kjimg10.360buyimg.com/ott/jfs/t1/110076/36/35421/55176/63ba2607Fe84f89cc/b47347fa7e94bc50.png)](https://kjimg10.360buyimg.com/ott/jfs/t1/110076/36/35421/55176/63ba2607Fe84f89cc/b47347fa7e94bc50.png)

大佬可以在readme里面提示一下,让后来人就不要再浪费时间了

**Comment by XuanRanDev** [comment]
已知的，目前只有华为云还没被拉黑

**Comment by 96368a** [comment]
> 已知的，目前只有华为云还没被拉黑

各家的云函数有测试过吗

**Comment by XuanRanDev** [comment]
> > 已知的，目前只有华为云还没被拉黑
> 
> 各家的云函数有测试过吗

只测试了腾讯云，同样被拉黑，阿里云应该也是，目前应该只有华为云还好好的

**Comment by 96368a** [comment]
> > > 已知的，目前只有华为云还没被拉黑
> > 
> > 
> > 各家的云函数有测试过吗
> 
> 只测试了腾讯云，同样被拉黑，阿里云应该也是，目前应该只有华为云还好好的

测试了一下，百度云函数没有被拉黑，而且也有免费额度

**Comment by 96368a** [comment]
增加百度云函数部署,[我frok的项目](https://github.com/96368a/AutoGongXueYun)

**Comment by XuanRanDev** [comment]
如果可以的话，可以提交一个pr

**Comment by XuanRanDev** [comment]
我觉得你可以优化一下代码和文件名，然后提交一个pr，或者我直接拷贝你修改过的代码，pr的时候合作提交。

**Comment by 96368a** [comment]
> 我觉得你可以优化一下代码和文件名，然后提交一个pr，或者我直接拷贝你修改过的代码，pr的时候合作提交。

不用pr了，百度云函数的ip已经被封了🥲🥲

**Comment by XuanRanDev** [comment]
> > 我觉得你可以优化一下代码和文件名，然后提交一个pr，或者我直接拷贝你修改过的代码，pr的时候合作提交。
> 
> 不用pr了，百度云函数的ip已经被封了🥲🥲

不会吧，这么快

**Comment by XuanRanDev** [comment]
已合并到master，谢谢😁。 #19 #21
