### ISSUE TITLE
自己服务器无法运行!

### ISSUE THREAD

**Issue by h1096224896** [XuanRanDev/Auto-GongXueYun#31]
在服务器运行之后,就卡在找到配置文件,将从配置文件读取信息,,然而本地运行就可以秒过!,不知道是什么原因

**Comment by XuanRanDev** [comment]
首先请给star避免白嫖，其次那是因为你服务器IP被拉黑了，再等会就给你报打卡失败了

**Comment by h1096224896** [comment]
刚才看了日志确实是网络原因,IP被拉黑了还有救吗

**Comment by XuanRanDev** [comment]
> 刚才看了日志确实是网络原因,IP被拉黑了还有救吗

使用代理服务器
