### ISSUE TITLE
请问老师打卡应该改哪里？

### ISSUE THREAD

**Issue by SKLMTCHEN1** [XuanRanDev/Auto-GongXueYun#33]
大佬好，我把url改成了：
url = "https://api.moguding.net:9000/practice/plan/v3/getPlanByTea"（原来最后3位是Stu）
roleKey改成了'teacher'（原来是student）
但还是报错“data”，请问还需要改哪里吗？还是说url没改对？多谢！

**Comment by XuanRanDev** [comment]
我没老师账号我也不知道是什么，你可以自己抓包看一下请求和rolekey是什么

**Comment by SKLMTCHEN1** [comment]
> 我没老师账号我也不知道是什么，你可以自己抓包看一下请求是什么

感谢指导~请问您是怎么抓包的？手机上小黄鸟抓包会直接连不上网，PC上模拟器只有逍遥模拟器软件不会闪退，而且Proxifier和BurpSuite一设置代理就会连不上网，最近是不是工学云做了防检测抓包的功能呢？加了SSL Pinning吗？

**Comment by XuanRanDev** [comment]
> > 我没老师账号我也不知道是什么，你可以自己抓包看一下请求是什么
> 
> 感谢指导~请问您是怎么抓包的？手机上小黄鸟抓包会直接连不上网，PC上模拟器只有逍遥模拟器软件不会闪退，而且Proxifier和BurpSuite一设置代理就会连不上网，最近是不是工学云做了防检测抓包的功能呢？加了SSL Pinning吗？
> 

连不上网搜索justTrustMe模块取消工学云的证书固定就可以了
