### ISSUE TITLE
同一个网络下Linux系统报错，而Windows没有问题。

### ISSUE THREAD

**Issue by liangcun8** [XuanRanDev/Auto-GongXueYun#36]
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
![4a423a436f1fdde1ea8511331b007b0d_](https://user-images.githubusercontent.com/95033824/233993777-5ad2b285-9ee0-4cec-94bf-cfc871b38ddb.png)
![249c17ac0c5b7bd190fff3f14ff7e34d_](https://user-images.githubusercontent.com/95033824/233993826-e557105c-76a3-4353-9b44-04d81976f0f7.png)

**Comment by XuanRanDev** [comment]
似乎是你没配置号
